[build]
  command = "pnpm --filter @tobie/web db:generate && pnpm turbo run build --filter=@tobie/web"
  publish = "apps/web/.next"

[functions]
  external_node_modules = ["@prisma/client", "prisma", "@auth/prisma-adapter"]
  included_files = ["node_modules/.prisma/client/libquery_engine-rhel-openssl-3.0.x.so.node"]

[dev]
  command = "pnpm dev"

[[plugins]]
  package = "@netlify/plugin-nextjs"
