[build]
  command = "pnpm install && pnpm --filter @tobie/web db:generate && pnpm turbo run build --filter=@tobie/web..."
  publish = "apps/web/.next"

[dev]
  command = "pnpm dev"

[[plugins]]
  package = "@netlify/plugin-nextjs"
